# Datasets
DATASET_NAME = 'dataset_name'
PROBLEM_TYPE = 'problem_type'
PROBLEM_SIZE = 'problem_size'
USE_TARGET_EMBEDDING = 'use_target_embedding'
REGRESSION = 'regression'
CLASSIFICATION = 'classification'
EXPLAINABILITY = 'explainability'

# Discretización de variables continuas
N_QUANTILE = 'n_quantile'
OUTPUT_DISTRIBUTION = 'output_distribution'

# Split train/test
PERCENTAGE_TEST = 'percentage_test'

# Brain struct
BRAIN_PARAMS = 'brain_params'
COMMON = 'common'
INPUT_EMBEDDING = 'input_embedding'
INPUT_GRAPH_EMBEDDING = 'input_graph_embedding'
INPUT_MLP_EMBEDDING = 'input_mlp_embedding'
GRAPH_EMBEDDING = 'graph_embedding'
TRANSFORMER_EMBEDDING = 'transformer_embedding'
DECODER = 'decoder'
TRAINER_PARAMS = 'trainer_params'
ENABLE = 'enable'
INPUT_EMBEDDING_CON = 'input_embedding_con'

# Brain
LATENT_SPACE_SIZE = 'latent_space_size'
CLS_NUM = 'cls_num'
DROPOUT = 'dropout'
GNN_TYPE = 'gnn_type'
GNN_NUM = 'gnn_num'
IN_GNN = 'in_gnn'
IN_MULTI_CHANNEL_GNN = 'in_multichannel_gnn'
IN_MLP_DEEP = 'in_mlp_deep'
IN_CHANNELS = 'in_channels'
IN_CHANNEL_AGG = 'in_channel_agg'
IN_CHANNEL_AGG_CONCAT = 'concat'
IN_CHANNEL_AGG_MLP = 'mlp'
IN_CHANNEL_AGG_SUM = 'sum'
IN_TRANSFORMER = 'in_transformer'
GAT_GNN = 'gat_gnn'
GAT_HEADS = 'gat_heads'
TRANSFORMER_TYPE = 'transformer_type'
TRANSFORMER_NUM = 'transformer_num'
TRANSFORMER_HEADS = 'transformer_heads'
DECODER_DEEP = 'decoder_deep'
DECODER_TYPE = 'decoder_type'
TRAINABLE_PARAMS_NUM = 'trainable_params_num'

# Trainer
EPOCHS = 'epochs'
BATCH_SIZE = 'batch_size'
TRAIN_LEARNING_RATE = 'training_learning_rate'
DEVICE = 'device'
METRIC = 'metric'
METRIC_LIST = 'metric_list'
EPOCH = 'epoch'
TRAINING_TITLE = 'TRAINING'
TRAIN_TITLE = 'TRAIN'
TRAIN_TIME = 'train_time'
TEST_TIME = 'test_time'
TEST_TITLE = 'TEST'
MEAN = 'mean'
STD = 'sdt'
PATH = 'path'
